"""Computers in Settings > Devices, and every Start menu app on the PC.

The Windows desktop MCP server could launch six hard-coded apps while the PC
has ~300 in its Start menu, and the Devices tab did not show the PC or the
Linux laptop at all. These cover the discovery, the launch rule (only names
from Windows' own list, never a path), and the tab's endpoints.
"""
import importlib.util
import json
import os

from fastapi import FastAPI
from fastapi.testclient import TestClient

from routes import device_routes

_HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_spec = importlib.util.spec_from_file_location(
    "desktop_mcp_server", os.path.join(_HERE, "tools", "mcp", "desktop_mcp_server.py"))
dms = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(dms)

# A slice of the real Get-StartApps output from the PC, plus the kinds of
# entry that must be dropped.
START_JSON = json.dumps([
    {"Name": "Adobe Photoshop 2025", "AppID": "{6D80}\\Adobe\\Adobe Photoshop 2025\\Photoshop.exe"},
    {"Name": "Adobe Premiere Pro 2025", "AppID": "{6D80}\\Adobe\\Adobe Premiere Pro 2025\\Adobe Premiere Pro.exe"},
    {"Name": "Audacity", "AppID": "D:\\Program Files\\Audacity\\Audacity.exe"},
    {"Name": "Arduino IDE", "AppID": "cc.arduino.IDE2"},
    {"Name": "Arduino Cloud Agent", "AppID": "C:\\Users\\j\\ArduinoCloudAgent\\Arduino_Cloud_Agent.exe"},
    {"Name": "ASTRONEER", "AppID": "steam://rungameid/361420"},
    {"Name": "Notepad", "AppID": "Microsoft.WindowsNotepad_8wekyb3d8bbwe!App"},
    {"Name": "Uninstall Audacity", "AppID": "D:\\Program Files\\Audacity\\unins000.exe"},
    {"Name": "Python 3.12 Manuals (64-bit)", "AppID": "C:\\Python312\\Doc\\python3120.chm"},
    {"Name": "LG Monitor App Installer", "AppID": "C:\\LG\\setup.exe"},
    {"Name": "Recovery Drive", "AppID": "Microsoft.AutoGenerated.{ABC}"},
    {"Name": "Notepad", "AppID": "duplicate"},
])


def test_start_menu_parse_drops_uninstallers_docs_and_dupes():
    apps = dms._parse_start_apps(START_JSON)
    names = [a["name"] for a in apps]
    assert names == sorted(names, key=str.lower)
    assert "Adobe Photoshop 2025" in names and "ASTRONEER" in names
    for gone in ("Uninstall Audacity", "Python 3.12 Manuals (64-bit)",
                 "LG Monitor App Installer", "Recovery Drive"):
        assert gone not in names, gone
    assert names.count("Notepad") == 1


def test_start_menu_parse_handles_one_app_and_nothing():
    one = json.dumps({"Name": "Audacity", "AppID": "D:\\Audacity.exe"})
    assert dms._parse_start_apps(one) == [{"name": "Audacity", "app_id": "D:\\Audacity.exe"}]
    assert dms._parse_start_apps("") == []


def test_find_start_app_exact_prefix_and_ambiguous():
    apps = dms._parse_start_apps(START_JSON)
    assert dms._find_start_app(apps, "audacity")["app"]["name"] == "Audacity"
    assert dms._find_start_app(apps, "premiere")["app"]["name"] == "Adobe Premiere Pro 2025"
    assert set(dms._find_start_app(apps, "arduino")["candidates"]) == {"Arduino IDE", "Arduino Cloud Agent"}
    assert dms._find_start_app(apps, "zzz") == {"candidates": []}


def test_launch_app_opens_start_menu_entries_by_windows_appid(monkeypatch):
    apps = dms._parse_start_apps(START_JSON)
    monkeypatch.setattr(dms, "_start_apps", lambda refresh=False: apps)
    ran = []
    monkeypatch.setattr(dms, "_run", lambda argv, timeout=30: ran.append(argv) or {"ok": True})

    r = dms.launch_app("photoshop")
    assert r["ok"] and r["app"] == "Adobe Photoshop 2025"
    assert ran == [["explorer.exe",
                    "shell:AppsFolder\\{6D80}\\Adobe\\Adobe Photoshop 2025\\Photoshop.exe"]]


def test_launch_app_never_runs_what_the_caller_typed(monkeypatch):
    apps = dms._parse_start_apps(START_JSON)
    monkeypatch.setattr(dms, "_start_apps", lambda refresh=False: apps)
    ran = []
    monkeypatch.setattr(dms, "_run", lambda argv, timeout=30: ran.append(argv) or {"ok": True})
    for evil in ("C:\\Windows\\System32\\cmd.exe", "calc.exe & del *", "uninstall audacity", "arduino"):
        r = dms.launch_app(evil)
        assert r["ok"] is False, evil
    assert ran == []


def test_list_apps_filters_and_keeps_curated(monkeypatch):
    apps = dms._parse_start_apps(START_JSON)
    monkeypatch.setattr(dms, "_start_apps", lambda refresh=False: apps)
    monkeypatch.setattr(dms, "_processes", lambda: {})
    r = dms.list_apps("adobe")
    assert r["installed"] == ["Adobe Photoshop 2025", "Adobe Premiere Pro 2025"]
    full = dms.list_apps()
    assert {a["app"] for a in full["curated"]} >= {"vscode", "resolve"}
    assert full["installed_total"] == len(apps)


def test_tool_output_parser_reads_joined_objects():
    assert device_routes._parse_tool_json('{"a": 1}{"b": 2}') == [{"a": 1}, {"b": 2}]
    assert device_routes._parse_tool_json('{"a": 1}\n{"b": 2}') == [{"a": 1}, {"b": 2}]
    assert device_routes._parse_tool_json('{"apps": []}') == {"apps": []}
    assert device_routes._parse_tool_json("") is None


def test_apps_normalized_for_windows_old_windows_and_linux():
    win = device_routes._apps_from({
        "curated": [{"app": "vscode", "description": "Visual Studio Code Insiders", "running": True}],
        "installed": ["Audacity"], "installed_total": 1, "note": ""})
    assert win["apps"][0] == {"name": "Visual Studio Code Insiders", "launch": "vscode",
                              "running": True, "curated": True}
    assert win["apps"][1] == {"name": "Audacity", "launch": "Audacity"}
    assert win["total"] == 2

    old = device_routes._apps_from([{"app": "resolve", "description": "DaVinci Resolve Studio"}])
    assert old["apps"][0]["launch"] == "resolve"

    linux = device_routes._apps_from({"ok": True, "count": 2, "apps": [
        {"id": "org.kde.dolphin", "name": "Dolphin"}, {"id": "firefox", "name": "Firefox"}]})
    assert [a["launch"] for a in linux["apps"]] == ["org.kde.dolphin", "firefox"]
    assert linux["total"] == 2


class _FakeMgr:
    def __init__(self):
        self.calls = []

    def get_all_tools(self):
        return [{"server_id": "pc", "name": "list_apps"}, {"server_id": "pc", "name": "launch_app"},
                {"server_id": "pc", "name": "screenshot"}]

    def get_server_status(self, sid):
        return ({"status": "connected", "tool_count": 12} if sid == "pc"
                else {"status": "error", "error": "unhandled errors in a TaskGroup"})

    async def call_tool(self, name, args):
        self.calls.append((name, args))
        if name.endswith("list_apps"):
            return {"stdout": json.dumps({"curated": [], "installed": ["Audacity"],
                                          "installed_total": 1, "note": ""}), "exit_code": 0}
        return {"stdout": json.dumps({"ok": True, "app": args["app"]}), "exit_code": 0}


def test_computer_routes(monkeypatch):
    mgr = _FakeMgr()
    monkeypatch.setattr(device_routes, "_mcp", lambda: mgr)
    monkeypatch.setattr(device_routes, "_configured_servers", lambda: [
        {"id": "pc", "name": "windows-desktop", "url": "http://100.1.1.1:8931/sse", "transport": "sse", "enabled": True},
        {"id": "lap", "name": "linux-laptop", "url": "http://lap:8932/sse", "transport": "sse", "enabled": True}])
    monkeypatch.setattr(device_routes, "require_admin", lambda request: None)
    app = FastAPI()
    app.include_router(device_routes.setup_device_routes())
    c = TestClient(app)

    comps = {x["name"]: x for x in c.get("/api/devices/computers").json()["computers"]}
    assert comps["windows-desktop"]["apps"] and comps["windows-desktop"]["status"] == "connected"
    assert comps["linux-laptop"]["status"] == "error"
    assert comps["linux-laptop"]["error"].startswith("Can't reach it")

    apps = c.get("/api/devices/computers/pc/apps?match=aud").json()
    assert apps["apps"] == [{"name": "Audacity", "launch": "Audacity"}]
    assert mgr.calls[-1] == ("mcp__pc__list_apps", {"match": "aud"})

    r = c.post("/api/devices/computers/pc/launch", json={"app": "Audacity"}).json()
    assert r["ok"] and mgr.calls[-1] == ("mcp__pc__launch_app", {"app": "Audacity"})
    assert c.post("/api/devices/computers/pc/launch", json={}).status_code == 400
