"""The Claude sessions page (src/claude_code_sessions.py,
routes/claude_sessions_routes.py): Claude Code's own transcripts under
~/.claude/projects, read in the browser.

Asked for: browse and read his Claude Code sessions in Odysseus instead of
opening the Terminal. What matters:

  * a transcript becomes readable turns: prompts, replies, tool calls with a
    one-line summary, results cut short, and none of the bookkeeping;
  * only a real project dir and a UUID are ever opened, so a request can't
    read anything else on the box;
  * big files are paged from the end and followed from an offset, never
    read whole, and a half-written last line waits for the next poll;
  * the list has titles, branch, message counts and live sessions first;
  * only an admin gets any of it.
"""
import json
import os
import time

import pytest
from fastapi import FastAPI
from starlette.testclient import TestClient

from routes import claude_sessions_routes
from src import claude_code_sessions as ccs

SID = "11111111-2222-4333-8444-555555555555"
SID2 = "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee"
PROJ = "-home-jaron-proj"


def _ev(kind, **kw):
    d = {"type": kind, "sessionId": SID, "cwd": "/home/jaron/proj", "gitBranch": "main",
         "timestamp": "2026-10-04T12:00:00.000Z"}
    d.update(kw)
    return d


def _user(text, **kw):
    return _ev("user", message={"role": "user", "content": text}, **kw)


def _assistant(*blocks, model="claude-opus-5"):
    # Real assistant lines carry "message" (with its role) before "type".
    return {"parentUuid": None, "isSidechain": False,
            "message": {"model": model, "role": "assistant", "content": list(blocks)},
            "type": "assistant", "cwd": "/home/jaron/proj", "gitBranch": "main",
            "timestamp": "2026-10-04T12:00:01.000Z"}


def _result(tool_id, text, is_error=False):
    return _ev("user", message={"role": "user", "content": [
        {"type": "tool_result", "tool_use_id": tool_id, "content": text, "is_error": is_error}]})


def _write(path, events, tail=""):
    with open(path, "w") as f:
        for e in events:
            f.write(json.dumps(e, separators=(",", ":")) + "\n")
        f.write(tail)


@pytest.fixture
def home(tmp_path, monkeypatch):
    root = tmp_path / "projects"
    (root / PROJ).mkdir(parents=True)
    monkeypatch.setenv("CLAUDE_PROJECTS_DIR", str(root))
    monkeypatch.setenv("CLAUDE_JOBS_DIR", str(tmp_path / "jobs"))
    ccs._CACHE.clear()
    return root


def _transcript(home, sid=SID, events=None, tail=""):
    path = home / PROJ / f"{sid}.jsonl"
    _write(path, events if events is not None else [
        {"type": "custom-title", "customTitle": "Fix the login page", "sessionId": SID},
        _user("<local-command-caveat>Caveat: generated by local commands</local-command-caveat>", isMeta=True),
        _user("please fix the login page"),
        _assistant({"type": "thinking", "thinking": "", "signature": "x"},
                   {"type": "text", "text": "Looking at it."},
                   {"type": "tool_use", "id": "t1", "name": "Bash",
                    "input": {"command": "ls -la src", "description": "List the source"}}),
        _result("t1", "a.py\nb.py"),
        {"type": "attachment", "attachment": {"type": "file", "content": "x" * 5000}},
        {"type": "file-history-snapshot", "snapshot": {}},
        _assistant({"type": "text", "text": "**Done.**"}),
    ], tail)
    return path


# ── Parsing ─────────────────────────────────────────────────────────────

def test_a_transcript_becomes_readable_turns(home):
    page = ccs.read_page(str(_transcript(home)))
    kinds = [(t["kind"], t.get("text") or t.get("name")) for t in page["turns"]]
    assert kinds == [("user", "please fix the login page"), ("assistant", "Looking at it."),
                     ("tool", "Bash"), ("tool_result", "a.py\nb.py"), ("assistant", "**Done.**")]
    tool = page["turns"][2]
    assert tool["id"] == "t1" and tool["summary"] == "List the source: ls -la src"
    assert page["turns"][3]["id"] == "t1" and page["start"] == 0


def test_tool_results_and_long_text_are_cut_short():
    long = "line\n" * 2000
    turns = ccs.parse_event(_result("t9", long, is_error=True))
    assert turns[0]["truncated"] and len(turns[0]["text"]) <= ccs.RESULT_CAP + 1
    assert turns[0]["is_error"]
    blocks = [{"type": "text", "text": "out"}, {"type": "image", "source": {}}]
    assert ccs.parse_event(_result("t9", blocks))[0]["text"] == "out\n[image]"


@pytest.mark.parametrize("name,inp,want", [
    ("Read", {"file_path": "/a/b.py", "limit": 10}, "/a/b.py"),
    ("Grep", {"pattern": "def x", "path": "src"}, "def x in src"),
    ("WebFetch", {"url": "https://example.com", "prompt": "summarize"}, "https://example.com"),
    ("Custom", {"n": 1}, '{"n": 1}'),
])
def test_tool_input_summaries(name, inp, want):
    assert ccs.summarize_input(name, inp) == want


def test_a_tool_summary_is_one_short_line():
    s = ccs.summarize_input("Bash", {"command": "echo hi\n" * 200})
    assert "\n" not in s and len(s) <= ccs.INPUT_SUMMARY_CAP + 1


def test_slash_commands_compact_summaries_and_system_notes():
    cmd = _user("<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus</command-args>")
    assert ccs.parse_event(cmd) == [{"kind": "user", "text": "/model opus", "truncated": False,
                                     "ts": "2026-10-04T12:00:00.000Z", "sidechain": False}]
    summ = ccs.parse_event(_user("Summary: earlier work", isCompactSummary=True))
    assert summ[0]["kind"] == "summary"
    assert ccs.parse_event(_ev("system", subtype="compact_boundary"))[0]["text"] == "Conversation compacted"
    assert ccs.parse_event(_ev("system", subtype="turn_duration")) == []
    assert ccs.parse_event({"type": "last-prompt", "lastPrompt": "x"}) == []


def test_a_huge_line_is_skipped_not_read(home, monkeypatch):
    monkeypatch.setattr(ccs, "MAX_LINE", 2000)
    path = _transcript(home, events=[_user("before"), _result("t1", "y" * 10000), _user("after")])
    page = ccs.read_page(str(path))
    assert [t["kind"] for t in page["turns"]] == ["user", "system", "user"]
    assert "too large" in page["turns"][1]["text"]
    follow = ccs.read_after(str(path), 0)
    assert [t["kind"] for t in follow["turns"]] == ["user", "system", "user"]
    assert follow["end"] == os.path.getsize(path)


# ── Paging and following ────────────────────────────────────────────────

def test_pages_go_backwards_and_meet_the_start(home):
    path = str(_transcript(home, events=[_user(f"prompt {i}") for i in range(25)]))
    seen = []
    page = ccs.read_page(path, limit=10)
    seen = [t["text"] for t in page["turns"]] + seen
    assert seen[-1] == "prompt 24" and len(seen) == 10
    while page["start"]:
        page = ccs.read_page(path, before=page["start"], limit=10)
        seen = [t["text"] for t in page["turns"]] + seen
    assert seen == [f"prompt {i}" for i in range(25)]


def test_lines_backward_matches_a_forward_read(tmp_path):
    lines = [("x" * (i * 37 % 900)) + str(i) for i in range(300)]
    p = tmp_path / "f.jsonl"
    p.write_bytes(("\n".join(lines) + "\n").encode())
    with open(p, "rb") as f:
        got = [(off, line.decode()) for off, line, _n in ccs.lines_backward(f, p.stat().st_size, block=64)]
    assert [line for _o, line in reversed(got)] == lines
    data = p.read_bytes()
    assert all(data[off:off + len(line)].decode() == line for off, line in got)


def test_a_half_written_line_waits_for_the_next_poll(home):
    path = _transcript(home, events=[_user("one")], tail='{"type":"user","message":{"role":"user","content":"tw')
    page = ccs.read_page(str(path))
    assert [t["text"] for t in page["turns"]] == ["one"]
    assert page["end"] < os.path.getsize(path)
    assert ccs.read_after(str(path), page["end"])["turns"] == []
    with open(path, "a") as f:
        f.write('o"},"timestamp":"2026-10-04T12:01:00Z"}\n')
        f.write(json.dumps(_user("three"), separators=(",", ":")) + "\n")
    more = ccs.read_after(str(path), page["end"])
    assert [t["text"] for t in more["turns"]] == ["two", "three"]
    assert more["end"] == os.path.getsize(path) and not more["reset"]


def test_a_rewritten_file_starts_over(home):
    path = _transcript(home)
    assert ccs.read_after(str(path), os.path.getsize(path) + 100)["reset"]


# ── The list ────────────────────────────────────────────────────────────

def test_the_list_has_titles_counts_and_live_first(home):
    old = _transcript(home)
    os.utime(old, (time.time() - 3600, time.time() - 3600))
    new = home / PROJ / f"{SID2}.jsonl"
    _write(new, [_user("<command-name>/clear</command-name>"), _user("add a dark mode"),
                 _assistant({"type": "text", "text": "ok"})])
    (home / PROJ / "not-a-session.jsonl").write_text("{}\n")
    (home / PROJ / SID).mkdir()                   # a session's sidecar dir, not a transcript
    sessions = ccs.list_sessions()
    assert [s["id"] for s in sessions] == [SID2, SID]
    live, done = sessions
    assert live["live"] and not done["live"]
    assert live["title"] == "add a dark mode" and done["title"] == "Fix the login page"
    assert done["git_branch"] == "main" and done["cwd"] == "/home/jaron/proj" and done["project"] == PROJ
    # Prompts and replies, tool results included, bookkeeping not.
    assert done["message_count"] == 5 and live["message_count"] == 3


def test_the_count_follows_appends(home):
    path = _transcript(home)
    assert ccs.list_sessions()[0]["message_count"] == 5
    with open(path, "a") as f:
        f.write(json.dumps(_user("more"), separators=(",", ":")) + "\n")
        f.write('{"type":"user","message":{"role":"user","content":"half')
    assert ccs.list_sessions()[0]["message_count"] == 6
    with open(path, "a") as f:
        f.write('"}}\n')
    assert ccs.list_sessions()[0]["message_count"] == 7


def test_a_background_job_is_named(home, tmp_path):
    _transcript(home)
    job = tmp_path / "jobs" / SID[:8]
    job.mkdir(parents=True)
    (job / "state.json").write_text(json.dumps({"state": "done", "name": "Login fix", "detail": "Fixed",
                                                "linkScanPath": str(home / PROJ / f"{SID}.jsonl")}))
    assert ccs.list_sessions()[0]["job"] == {"state": "done", "name": "Login fix", "detail": "Fixed"}


# ── Path safety ─────────────────────────────────────────────────────────

@pytest.mark.parametrize("project,sid", [
    ("..", SID), ("../..", SID), (PROJ + "/..", SID), ("-home-jaron-other", SID), ("", SID),
    (PROJ, "../" + SID), (PROJ, SID + ".jsonl"), (PROJ, SID2.upper()), (PROJ, "not-a-uuid"),
    (PROJ, "11111111-2222-4333-8444-55555555555"), ("%2e%2e", SID), (PROJ, ""),
])
def test_only_real_projects_and_uuids_are_opened(home, project, sid):
    _transcript(home)
    assert ccs.transcript_path(project, sid) is None


def test_a_symlink_out_of_the_projects_dir_is_refused(home, tmp_path):
    secret = tmp_path / "secret.jsonl"
    secret.write_text(json.dumps(_user("secret")) + "\n")
    os.symlink(secret, home / PROJ / f"{SID2}.jsonl")
    os.symlink(tmp_path, home / "-linked-project")
    assert ccs.transcript_path(PROJ, SID2) is None
    assert "-linked-project" not in ccs.project_names()
    assert ccs.list_sessions() == []
    _transcript(home)
    assert ccs.transcript_path(PROJ, SID) == os.path.realpath(home / PROJ / f"{SID}.jsonl")


# ── The routes ──────────────────────────────────────────────────────────

class _Auth:
    is_configured = True

    def __init__(self, admins):
        self.admins = admins

    def is_admin(self, user):
        return user in self.admins


def _app(user=None, admins=()):
    app = FastAPI()
    app.state.auth_manager = _Auth(set(admins))

    @app.middleware("http")
    async def _who(request, call_next):
        request.state.current_user = user
        return await call_next(request)

    app.include_router(claude_sessions_routes.setup_claude_sessions_routes())
    return app


def test_only_an_admin_gets_anything(home, monkeypatch):
    monkeypatch.setenv("AUTH_ENABLED", "true")
    _transcript(home)
    for user in (None, "guest"):
        c = TestClient(_app(user=user, admins={"jaron"}))
        assert c.get("/api/claude_sessions").status_code == 403
        assert c.get(f"/api/claude_sessions/{PROJ}/{SID}").status_code == 403
        assert c.get(f"/api/claude_sessions/{PROJ}/{SID}/updates?after=0").status_code == 403
    c = TestClient(_app(user="jaron", admins={"jaron"}))
    assert c.get("/api/claude_sessions").json()["sessions"][0]["id"] == SID


def test_the_routes_page_and_follow(home, monkeypatch):
    monkeypatch.setenv("AUTH_ENABLED", "true")
    path = _transcript(home)
    c = TestClient(_app(user="jaron", admins={"jaron"}))
    d = c.get(f"/api/claude_sessions/{PROJ}/{SID}?limit=2").json()
    assert [t["kind"] for t in d["turns"]] == ["tool_result", "assistant"] and d["start"] > 0
    assert d["session"]["title"] == "Fix the login page" and d["end"] == os.path.getsize(path)
    older = c.get(f"/api/claude_sessions/{PROJ}/{SID}?before={d['start']}").json()
    assert older["turns"][0]["text"] == "please fix the login page" and older["start"] == 0
    with open(path, "a") as f:
        f.write(json.dumps(_user("next"), separators=(",", ":")) + "\n")
    up = c.get(f"/api/claude_sessions/{PROJ}/{SID}/updates?after={d['end']}").json()
    assert [t["text"] for t in up["turns"]] == ["next"] and up["session"]["live"]


def test_the_routes_refuse_unknown_sessions(home, monkeypatch):
    monkeypatch.setenv("AUTH_ENABLED", "true")
    _transcript(home)
    c = TestClient(_app(user="jaron", admins={"jaron"}))
    for url in (f"/api/claude_sessions/{PROJ}/{SID2}", f"/api/claude_sessions/-nope/{SID}",
                f"/api/claude_sessions/{PROJ}/..%2F..%2Fetc", f"/api/claude_sessions/..%2F/{SID}/updates"):
        assert c.get(url).status_code == 404, url
